image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
    - target/Systera.jar

  script:
  # Run Maven
  - mvn clean package

deploy:
  stage: deploy
  script:
  - "curl -X POST -H \"PRIVATE-TOKEN: ${STARTAIL_AGENT_KEY}\" 'https://gitlab.com/api/v4/projects/startail%2Fmcserver/pipeline?ref=master'"