// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systera.proto

package net.synchthia.api.systera;

public final class SysteraProtos {
  private SysteraProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InitPlayerProfileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apipb.InitPlayerProfileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string playerUUID = 1;</code>
     */
    java.lang.String getPlayerUUID();
    /**
     * <code>optional string playerUUID = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerUUIDBytes();

    /**
     * <code>optional string playerName = 2;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <code>optional string playerName = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <code>optional string playerIPAddress = 3;</code>
     */
    java.lang.String getPlayerIPAddress();
    /**
     * <code>optional string playerIPAddress = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIPAddressBytes();
  }
  /**
   * <pre>
   * PLAYER PROFILE
   * </pre>
   *
   * Protobuf type {@code apipb.InitPlayerProfileRequest}
   */
  public  static final class InitPlayerProfileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:apipb.InitPlayerProfileRequest)
      InitPlayerProfileRequestOrBuilder {
    // Use InitPlayerProfileRequest.newBuilder() to construct.
    private InitPlayerProfileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InitPlayerProfileRequest() {
      playerUUID_ = "";
      playerName_ = "";
      playerIPAddress_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InitPlayerProfileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerUUID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              playerIPAddress_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.class, net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.Builder.class);
    }

    public static final int PLAYERUUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerUUID_;
    /**
     * <code>optional string playerUUID = 1;</code>
     */
    public java.lang.String getPlayerUUID() {
      java.lang.Object ref = playerUUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerUUID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string playerUUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerUUIDBytes() {
      java.lang.Object ref = playerUUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object playerName_;
    /**
     * <code>optional string playerName = 2;</code>
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string playerName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERIPADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object playerIPAddress_;
    /**
     * <code>optional string playerIPAddress = 3;</code>
     */
    public java.lang.String getPlayerIPAddress() {
      java.lang.Object ref = playerIPAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerIPAddress_ = s;
        return s;
      }
    }
    /**
     * <code>optional string playerIPAddress = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIPAddressBytes() {
      java.lang.Object ref = playerIPAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerIPAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerUUID_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, playerName_);
      }
      if (!getPlayerIPAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, playerIPAddress_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerUUID_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, playerName_);
      }
      if (!getPlayerIPAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, playerIPAddress_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest)) {
        return super.equals(obj);
      }
      net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest other = (net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest) obj;

      boolean result = true;
      result = result && getPlayerUUID()
          .equals(other.getPlayerUUID());
      result = result && getPlayerName()
          .equals(other.getPlayerName());
      result = result && getPlayerIPAddress()
          .equals(other.getPlayerIPAddress());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PLAYERUUID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerUUID().hashCode();
      hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + PLAYERIPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerIPAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PLAYER PROFILE
     * </pre>
     *
     * Protobuf type {@code apipb.InitPlayerProfileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apipb.InitPlayerProfileRequest)
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.class, net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.Builder.class);
      }

      // Construct using net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerUUID_ = "";

        playerName_ = "";

        playerIPAddress_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileRequest_descriptor;
      }

      public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest getDefaultInstanceForType() {
        return net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.getDefaultInstance();
      }

      public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest build() {
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest buildPartial() {
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest result = new net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest(this);
        result.playerUUID_ = playerUUID_;
        result.playerName_ = playerName_;
        result.playerIPAddress_ = playerIPAddress_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest) {
          return mergeFrom((net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest other) {
        if (other == net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest.getDefaultInstance()) return this;
        if (!other.getPlayerUUID().isEmpty()) {
          playerUUID_ = other.playerUUID_;
          onChanged();
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (!other.getPlayerIPAddress().isEmpty()) {
          playerIPAddress_ = other.playerIPAddress_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object playerUUID_ = "";
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public java.lang.String getPlayerUUID() {
        java.lang.Object ref = playerUUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerUUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerUUIDBytes() {
        java.lang.Object ref = playerUUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerUUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public Builder setPlayerUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerUUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public Builder clearPlayerUUID() {
        
        playerUUID_ = getDefaultInstance().getPlayerUUID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public Builder setPlayerUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerUUID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <code>optional string playerName = 2;</code>
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerName = 2;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerName = 2;</code>
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerName = 2;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object playerIPAddress_ = "";
      /**
       * <code>optional string playerIPAddress = 3;</code>
       */
      public java.lang.String getPlayerIPAddress() {
        java.lang.Object ref = playerIPAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerIPAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerIPAddress = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIPAddressBytes() {
        java.lang.Object ref = playerIPAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerIPAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerIPAddress = 3;</code>
       */
      public Builder setPlayerIPAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerIPAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerIPAddress = 3;</code>
       */
      public Builder clearPlayerIPAddress() {
        
        playerIPAddress_ = getDefaultInstance().getPlayerIPAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerIPAddress = 3;</code>
       */
      public Builder setPlayerIPAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerIPAddress_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:apipb.InitPlayerProfileRequest)
    }

    // @@protoc_insertion_point(class_scope:apipb.InitPlayerProfileRequest)
    private static final net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest();
    }

    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InitPlayerProfileRequest>
        PARSER = new com.google.protobuf.AbstractParser<InitPlayerProfileRequest>() {
      public InitPlayerProfileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InitPlayerProfileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InitPlayerProfileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InitPlayerProfileRequest> getParserForType() {
      return PARSER;
    }

    public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InitPlayerProfileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apipb.InitPlayerProfileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool hasProfile = 1;</code>
     */
    boolean getHasProfile();
  }
  /**
   * Protobuf type {@code apipb.InitPlayerProfileResponse}
   */
  public  static final class InitPlayerProfileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:apipb.InitPlayerProfileResponse)
      InitPlayerProfileResponseOrBuilder {
    // Use InitPlayerProfileResponse.newBuilder() to construct.
    private InitPlayerProfileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InitPlayerProfileResponse() {
      hasProfile_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InitPlayerProfileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              hasProfile_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.class, net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.Builder.class);
    }

    public static final int HASPROFILE_FIELD_NUMBER = 1;
    private boolean hasProfile_;
    /**
     * <code>optional bool hasProfile = 1;</code>
     */
    public boolean getHasProfile() {
      return hasProfile_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasProfile_ != false) {
        output.writeBool(1, hasProfile_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hasProfile_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hasProfile_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse)) {
        return super.equals(obj);
      }
      net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse other = (net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse) obj;

      boolean result = true;
      result = result && (getHasProfile()
          == other.getHasProfile());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HASPROFILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasProfile());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apipb.InitPlayerProfileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apipb.InitPlayerProfileResponse)
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.class, net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.Builder.class);
      }

      // Construct using net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hasProfile_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_InitPlayerProfileResponse_descriptor;
      }

      public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse getDefaultInstanceForType() {
        return net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.getDefaultInstance();
      }

      public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse build() {
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse buildPartial() {
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse result = new net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse(this);
        result.hasProfile_ = hasProfile_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse) {
          return mergeFrom((net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse other) {
        if (other == net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse.getDefaultInstance()) return this;
        if (other.getHasProfile() != false) {
          setHasProfile(other.getHasProfile());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean hasProfile_ ;
      /**
       * <code>optional bool hasProfile = 1;</code>
       */
      public boolean getHasProfile() {
        return hasProfile_;
      }
      /**
       * <code>optional bool hasProfile = 1;</code>
       */
      public Builder setHasProfile(boolean value) {
        
        hasProfile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hasProfile = 1;</code>
       */
      public Builder clearHasProfile() {
        
        hasProfile_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:apipb.InitPlayerProfileResponse)
    }

    // @@protoc_insertion_point(class_scope:apipb.InitPlayerProfileResponse)
    private static final net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse();
    }

    public static net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InitPlayerProfileResponse>
        PARSER = new com.google.protobuf.AbstractParser<InitPlayerProfileResponse>() {
      public InitPlayerProfileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InitPlayerProfileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InitPlayerProfileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InitPlayerProfileResponse> getParserForType() {
      return PARSER;
    }

    public net.synchthia.api.systera.SysteraProtos.InitPlayerProfileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FetchPlayerProfileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apipb.FetchPlayerProfileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string playerUUID = 1;</code>
     */
    java.lang.String getPlayerUUID();
    /**
     * <code>optional string playerUUID = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerUUIDBytes();
  }
  /**
   * Protobuf type {@code apipb.FetchPlayerProfileRequest}
   */
  public  static final class FetchPlayerProfileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:apipb.FetchPlayerProfileRequest)
      FetchPlayerProfileRequestOrBuilder {
    // Use FetchPlayerProfileRequest.newBuilder() to construct.
    private FetchPlayerProfileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchPlayerProfileRequest() {
      playerUUID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FetchPlayerProfileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerUUID_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.class, net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.Builder.class);
    }

    public static final int PLAYERUUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerUUID_;
    /**
     * <code>optional string playerUUID = 1;</code>
     */
    public java.lang.String getPlayerUUID() {
      java.lang.Object ref = playerUUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerUUID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string playerUUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerUUIDBytes() {
      java.lang.Object ref = playerUUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerUUID_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerUUID_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest)) {
        return super.equals(obj);
      }
      net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest other = (net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest) obj;

      boolean result = true;
      result = result && getPlayerUUID()
          .equals(other.getPlayerUUID());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PLAYERUUID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerUUID().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apipb.FetchPlayerProfileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apipb.FetchPlayerProfileRequest)
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.class, net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.Builder.class);
      }

      // Construct using net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerUUID_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileRequest_descriptor;
      }

      public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest getDefaultInstanceForType() {
        return net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.getDefaultInstance();
      }

      public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest build() {
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest buildPartial() {
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest result = new net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest(this);
        result.playerUUID_ = playerUUID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest) {
          return mergeFrom((net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest other) {
        if (other == net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest.getDefaultInstance()) return this;
        if (!other.getPlayerUUID().isEmpty()) {
          playerUUID_ = other.playerUUID_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object playerUUID_ = "";
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public java.lang.String getPlayerUUID() {
        java.lang.Object ref = playerUUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerUUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerUUIDBytes() {
        java.lang.Object ref = playerUUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerUUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public Builder setPlayerUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerUUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public Builder clearPlayerUUID() {
        
        playerUUID_ = getDefaultInstance().getPlayerUUID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerUUID = 1;</code>
       */
      public Builder setPlayerUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerUUID_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:apipb.FetchPlayerProfileRequest)
    }

    // @@protoc_insertion_point(class_scope:apipb.FetchPlayerProfileRequest)
    private static final net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest();
    }

    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchPlayerProfileRequest>
        PARSER = new com.google.protobuf.AbstractParser<FetchPlayerProfileRequest>() {
      public FetchPlayerProfileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FetchPlayerProfileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchPlayerProfileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchPlayerProfileRequest> getParserForType() {
      return PARSER;
    }

    public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FetchPlayerProfileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apipb.FetchPlayerProfileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */
    int getSettingsCount();
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */
    boolean containsSettings(
        java.lang.String key);
    /**
     * Use {@link #getSettingsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Boolean>
    getSettings();
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Boolean>
    getSettingsMap();
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */

    boolean getSettingsOrDefault(
        java.lang.String key,
        boolean defaultValue);
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */

    boolean getSettingsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code apipb.FetchPlayerProfileResponse}
   */
  public  static final class FetchPlayerProfileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:apipb.FetchPlayerProfileResponse)
      FetchPlayerProfileResponseOrBuilder {
    // Use FetchPlayerProfileResponse.newBuilder() to construct.
    private FetchPlayerProfileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchPlayerProfileResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FetchPlayerProfileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                settings_ = com.google.protobuf.MapField.newMapField(
                    SettingsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
              settings = input.readMessage(
                  SettingsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              settings_.getMutableMap().put(settings.getKey(), settings.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetSettings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.class, net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.Builder.class);
    }

    public static final int SETTINGS_FIELD_NUMBER = 1;
    private static final class SettingsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Boolean> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                  net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileResponse_SettingsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BOOL,
                  false);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Boolean> settings_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
    internalGetSettings() {
      if (settings_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SettingsDefaultEntryHolder.defaultEntry);
      }
      return settings_;
    }

    public int getSettingsCount() {
      return internalGetSettings().getMap().size();
    }
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */

    public boolean containsSettings(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSettings().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSettingsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getSettings() {
      return getSettingsMap();
    }
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Boolean> getSettingsMap() {
      return internalGetSettings().getMap();
    }
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */

    public boolean getSettingsOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetSettings().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bool&gt; settings = 1;</code>
     */

    public boolean getSettingsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetSettings().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
           : internalGetSettings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
        settings = SettingsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, settings);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
           : internalGetSettings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
        settings = SettingsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, settings);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse)) {
        return super.equals(obj);
      }
      net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse other = (net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse) obj;

      boolean result = true;
      result = result && internalGetSettings().equals(
          other.internalGetSettings());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetSettings().getMap().isEmpty()) {
        hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSettings().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apipb.FetchPlayerProfileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apipb.FetchPlayerProfileResponse)
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetSettings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableSettings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.class, net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.Builder.class);
      }

      // Construct using net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableSettings().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.synchthia.api.systera.SysteraProtos.internal_static_apipb_FetchPlayerProfileResponse_descriptor;
      }

      public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse getDefaultInstanceForType() {
        return net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.getDefaultInstance();
      }

      public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse build() {
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse buildPartial() {
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse result = new net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse(this);
        int from_bitField0_ = bitField0_;
        result.settings_ = internalGetSettings();
        result.settings_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse) {
          return mergeFrom((net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse other) {
        if (other == net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse.getDefaultInstance()) return this;
        internalGetMutableSettings().mergeFrom(
            other.internalGetSettings());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Boolean> settings_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
      internalGetSettings() {
        if (settings_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SettingsDefaultEntryHolder.defaultEntry);
        }
        return settings_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
      internalGetMutableSettings() {
        onChanged();;
        if (settings_ == null) {
          settings_ = com.google.protobuf.MapField.newMapField(
              SettingsDefaultEntryHolder.defaultEntry);
        }
        if (!settings_.isMutable()) {
          settings_ = settings_.copy();
        }
        return settings_;
      }

      public int getSettingsCount() {
        return internalGetSettings().getMap().size();
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */

      public boolean containsSettings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetSettings().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSettingsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean> getSettings() {
        return getSettingsMap();
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Boolean> getSettingsMap() {
        return internalGetSettings().getMap();
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */

      public boolean getSettingsOrDefault(
          java.lang.String key,
          boolean defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetSettings().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */

      public boolean getSettingsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetSettings().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSettings() {
        getMutableSettings().clear();
        return this;
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */

      public Builder removeSettings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableSettings().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean>
      getMutableSettings() {
        return internalGetMutableSettings().getMutableMap();
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */
      public Builder putSettings(
          java.lang.String key,
          boolean value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        getMutableSettings().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bool&gt; settings = 1;</code>
       */

      public Builder putAllSettings(
          java.util.Map<java.lang.String, java.lang.Boolean> values) {
        getMutableSettings().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:apipb.FetchPlayerProfileResponse)
    }

    // @@protoc_insertion_point(class_scope:apipb.FetchPlayerProfileResponse)
    private static final net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse();
    }

    public static net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchPlayerProfileResponse>
        PARSER = new com.google.protobuf.AbstractParser<FetchPlayerProfileResponse>() {
      public FetchPlayerProfileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FetchPlayerProfileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchPlayerProfileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchPlayerProfileResponse> getParserForType() {
      return PARSER;
    }

    public net.synchthia.api.systera.SysteraProtos.FetchPlayerProfileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_InitPlayerProfileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_InitPlayerProfileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_InitPlayerProfileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_InitPlayerProfileResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_FetchPlayerProfileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_FetchPlayerProfileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_FetchPlayerProfileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_FetchPlayerProfileResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_FetchPlayerProfileResponse_SettingsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_FetchPlayerProfileResponse_SettingsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsystera.proto\022\005apipb\"[\n\030InitPlayerProf" +
      "ileRequest\022\022\n\nplayerUUID\030\001 \001(\t\022\022\n\nplayer" +
      "Name\030\002 \001(\t\022\027\n\017playerIPAddress\030\003 \001(\t\"/\n\031I" +
      "nitPlayerProfileResponse\022\022\n\nhasProfile\030\001" +
      " \001(\010\"/\n\031FetchPlayerProfileRequest\022\022\n\npla" +
      "yerUUID\030\001 \001(\t\"\220\001\n\032FetchPlayerProfileResp" +
      "onse\022A\n\010settings\030\001 \003(\0132/.apipb.FetchPlay" +
      "erProfileResponse.SettingsEntry\032/\n\rSetti" +
      "ngsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\010:\0028\001" +
      "2\300\001\n\007Systera\022X\n\021InitPlayerProfile\022\037.apip",
      "b.InitPlayerProfileRequest\032 .apipb.InitP" +
      "layerProfileResponse\"\000\022[\n\022FetchPlayerPro" +
      "file\022 .apipb.FetchPlayerProfileRequest\032!" +
      ".apipb.FetchPlayerProfileResponse\"\000B*\n\031n" +
      "et.synchthia.api.systeraB\rSysteraProtosb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_apipb_InitPlayerProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apipb_InitPlayerProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_InitPlayerProfileRequest_descriptor,
        new java.lang.String[] { "PlayerUUID", "PlayerName", "PlayerIPAddress", });
    internal_static_apipb_InitPlayerProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apipb_InitPlayerProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_InitPlayerProfileResponse_descriptor,
        new java.lang.String[] { "HasProfile", });
    internal_static_apipb_FetchPlayerProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apipb_FetchPlayerProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_FetchPlayerProfileRequest_descriptor,
        new java.lang.String[] { "PlayerUUID", });
    internal_static_apipb_FetchPlayerProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apipb_FetchPlayerProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_FetchPlayerProfileResponse_descriptor,
        new java.lang.String[] { "Settings", });
    internal_static_apipb_FetchPlayerProfileResponse_SettingsEntry_descriptor =
      internal_static_apipb_FetchPlayerProfileResponse_descriptor.getNestedTypes().get(0);
    internal_static_apipb_FetchPlayerProfileResponse_SettingsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_FetchPlayerProfileResponse_SettingsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
